server:
  port: 5000
spring:
  application:
    name: zpp-crowd-project
  redis:
    host: 192.168.64.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: 
    access-key-secret: 
    bucket-domain: 
    bucket-name:
    end-point: 

ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 12000
