server:
  port: 5000
spring:
  application:
    name: zpp-crowd-project
  redis:
    host: 192.168.64.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI5tK1TTWo1f1LbbojPafF
    access-key-secret: JRCMJkJBkwmNqKtYWp0vNGgeSZg4WL
    bucket-domain: http://crowd-project-zpp.oss-cn-guangzhou.aliyuncs.com
    bucket-name: crowd-project-zpp
    end-point: http://oss-cn-guangzhou.aliyuncs.com

ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 12000